### ISSUE TITLE
Not enough precision for BigDecimal

### ISSUE THREAD

**Issue by QuantumDeveloper** [deveel/deveel-math#4]
Hi. Found another issue.

The following code:

```
BigDecimal bigDecimal = new BigDecimal(1000);
bigDecimal += 0.0005;
```

Will give result 1000.1, which is not what I expect.
Could this be workaround somehow or maybe I am missing something?

And another issue:

```
BigDecimal bigDecimal = new BigDecimal(1000.0005);
```

Will give me 
![image](https://cloud.githubusercontent.com/assets/6085009/8955280/e68b68ce-35f3-11e5-8bf8-7f5af5064cff.png)

Why not 1000.0005 exactly?

**Comment by tsutomi** [comment]
Making operations using native operators is prone to loss of precision, since (fixing #3 ) I'm using the precision model of the first operand for the operations (not just the division).
I'm not a mathematician by nature (I gave few exams at university, no more research), so I cannot help on the theory, but I ported part of the project Google Harmony (an open source version of the Java SDK for Android), to use the math features, integrating it with external additions and customizations. I'm developing projects for .NET that required such features (eg. [DeveelDB](http://github.com/deveel/deveeldb) ), so you can see it as an ancillary project.

Anyway, my best advice is to use the provided functions in the BigDecimal class rather than use the native operators, if you want to control the precision of the result.

**Comment by QuantumDeveloper** [comment]
Hm, but I cannot understand why operators and methods should work different?
Could you explain please?

**Comment by QuantumDeveloper** [comment]
Also even if I use methods instead of operators, issue 2 described in current topic is still present.

**Comment by tsutomi** [comment]
For what it concerns the usage of the methods instead of the native operators, this is important if you want to control the scale factor and the precision of the result of the operation.
If you specify a number with a lower precision, the result will be rounded, but if you don't specify any precision there are mathematical formulas applied to fill the number to the precise number of decimals. When you don't specify any scale or precision, the default precision for the corresponding value is applied.
Working with BigDecimals is not as straight forward as working with normal numbers: you must be precise on the kind of result you want to obtain.

To _fix_ the issue you're having, I suggest to specify a precision of 4, that tells the result must have only 4 digits after the decimal point (I haven't tested, but I'm pretty sure you will have the result expected)

**Comment by QuantumDeveloper** [comment]
But how to set precision if corresponding property cannot be set manually and in the methods present only MathContext, which is not the precision, I suppose.

Could you show me how to correct work with your library, please?

**Comment by tsutomi** [comment]
MathContext **IS** the precision of the number. Once you create a BigDecimal object, this is immutable by itself: it's normal that you cannot set any value. You will obtain new instances of BigDecimal by operating on the created object, that will not be changed.

I'm truly sorry that I haven't provided much information about the usage: as said, this is an ancillary project. I don't dedicate much time on it. There are hundreds of test cases in the NUnit project that explain the conditions for its usage.
